### ISSUE TITLE
Anything New?

### ISSUE THREAD

**Issue by kulkalkul** [MiniDigger/graal-test#2]
Hello, did you experiment with it further? I'm also experimenting with it and saw the project. First I thought it is abandoned, but yesterday I saw a message of you in GraalVM Gitter (which was from June).

Here is my experience if you wonder: 
I made a loader with Java. Being able to hot-load it, reload it is amazing. It theoretically opens Java libraries to JS and also makes you able to use JS libraries, which is another blast. I also like to write functional influenced code, so it increases my productivity.

**Comment by MiniDigger** [comment]
yeah, I did some more tests, but nothing exciting. I dont really have time for stuff nowadays :/

**Comment by MiniDigger** [comment]
idk if you care but I since prototyped this https://github.com/MiniDigger/MiniTestFramework

**Comment by kulkalkul** [comment]
Hey thanks! I was checking my active issues and saw this, thought it shouldn't be open and closed it 😅

About the repo, I recall talking about something in the paper discord server but I think it was before that. I'm not working on it anymore but thanks!
